services:
  - type: web
    name: spiritz-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: VITE_WS_URL
        value: https://spiritz-app.onrender.com
      - key: VITE_API_URL
        value: https://spiritz-app.onrender.com/api
    healthCheckPath: /api/health
    disk:
      name: data
      mountPath: /data
      sizeGB: 1